apiVersion: v1
kind: Secret
metadata:
  name: connection-strings
  namespace: cr
type: Opaque
data:
  CRIME_COSMOS_DB: bW9uZ29kYjovL2NyaW1lLXJlcG9ydGluZzp4Z291SVF5U3J2cWVSNGdWejMybzU5VzhvdnNVZTUzdWw0V3FRbE5Hb2ZYZzNMa21JRHdSdWk2U1hyeWxVSmhXRll6U1pBZ2VUanNKYjA4NEZiemt0dz09QGNyaW1lLXJlcG9ydGluZy5tb25nby5jb3Ntb3MuYXp1cmUuY29tOjEwMjU1Lz9zc2w9dHJ1ZSZyZXBsaWNhU2V0PWdsb2JhbGRiJnJldHJ5d3JpdGVzPWZhbHNlJm1heElkbGVUaW1lTVM9MTIwMDAwJmFwcE5hbWU9QGNyaW1lLXJlcG9ydGluZ0A=
  LAWENFORCEMENT_SQL_DB: U2VydmVyPXRjcDpjcmltZS1yZXBvcnRpbmcuZGF0YWJhc2Uud2luZG93cy5uZXQsMTQzMztJbml0aWFsIENhdGFsb2c9Q3JpbWVSZXBvcnRpbmc7UGVyc2lzdCBTZWN1cml0eSBJbmZvPUZhbHNlO1VzZXIgSUQ9Q3JpbWVSZXBvcnRpbmdBZG1pbjtQYXNzd29yZD1XZVIhUyFsbjNIYVNsMDtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOw==
