version: '3.4'

services:
  crimeapi:
    image: ${DOCKER_REGISTRY-}crimeapi
    build:
      context: .
      dockerfile: CrimeApi/Dockerfile
    restart: on-failure
    depends_on:
      - mongo

  lawenforcementapi:
    image: ${DOCKER_REGISTRY-}lawenforcementapi
    build:
      context: .
      dockerfile: LawEnforcementApi/Dockerfile
    restart: on-failure
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    restart: on-failure
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - law-enforcement-db:/var/opt/mssql

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - crime-event-db:/data/db

  seq:
    image: datalust/seq
    restart: on-failure
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "8081:80"
    volumes:
      - seq-logs:/data

volumes:
    law-enforcement-db:
    crime-event-db:
    seq-logs:
