version: '3.4'

services:
  crimeapi:
    image: ${DOCKER_REGISTRY-}crimeapi
    build:
      context: .
      dockerfile: CrimeApi/Dockerfile

  lawenforcementapi:
    image: ${DOCKER_REGISTRY-}lawenforcementapi
    build:
      context: .
      dockerfile: LawEnforcementApi/Dockerfile

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - law-enforcement-db:/var/opt/mssql

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db

volumes:
    law-enforcement-db:
    mongo-db-data:
