// <auto-generated />
using System;
using LawEnforcementApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawEnforcementApi.Migrations
{
    [DbContext(typeof(LawEnforcementContext))]
    [Migration("20221025122056_AddSeeder")]
    partial class AddSeeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LawEnforcementApi.Entities.CrimeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CrimeEventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OfficerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfficerId");

                    b.ToTable("CrimeEvents");
                });

            modelBuilder.Entity("LawEnforcementApi.Entities.Officer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CallSign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("OfficerRankId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CallSign")
                        .IsUnique();

                    b.HasIndex("OfficerRankId");

                    b.ToTable("Officers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01fde555-3de6-4ad2-ab32-ac725a6391e9"),
                            CallSign = "Tango-4",
                            OfficerRankId = new Guid("8960db50-77bd-4ea1-9038-952eb09a4eb5")
                        },
                        new
                        {
                            Id = new Guid("098603a4-895a-4b1e-85ee-bb83ed801c0a"),
                            CallSign = "Echo-1",
                            OfficerRankId = new Guid("1685cae0-71e4-4e76-83a9-5c9488b3942f")
                        },
                        new
                        {
                            Id = new Guid("b37e6518-d42b-4809-b848-c1501cf5af80"),
                            CallSign = "Charlie-10",
                            OfficerRankId = new Guid("ebb26b52-b7b9-42a2-8687-b06d1b2011ee")
                        });
                });

            modelBuilder.Entity("LawEnforcementApi.Entities.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1685cae0-71e4-4e76-83a9-5c9488b3942f"),
                            Name = "Lieutenant"
                        },
                        new
                        {
                            Id = new Guid("8960db50-77bd-4ea1-9038-952eb09a4eb5"),
                            Name = "Sergeant"
                        },
                        new
                        {
                            Id = new Guid("ebb26b52-b7b9-42a2-8687-b06d1b2011ee"),
                            Name = "Deputy"
                        });
                });

            modelBuilder.Entity("LawEnforcementApi.Entities.CrimeEvent", b =>
                {
                    b.HasOne("LawEnforcementApi.Entities.Officer", null)
                        .WithMany("CrimeEvents")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LawEnforcementApi.Entities.Officer", b =>
                {
                    b.HasOne("LawEnforcementApi.Entities.Rank", "OfficerRank")
                        .WithMany("Officers")
                        .HasForeignKey("OfficerRankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficerRank");
                });

            modelBuilder.Entity("LawEnforcementApi.Entities.Officer", b =>
                {
                    b.Navigation("CrimeEvents");
                });

            modelBuilder.Entity("LawEnforcementApi.Entities.Rank", b =>
                {
                    b.Navigation("Officers");
                });
#pragma warning restore 612, 618
        }
    }
}
